// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 3f31344502fe18872d5d025a6ce3bd12f7d0252b8c2c1f7e5610c347b8be7081

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "shadcn-theme";

export const themeNames: ThemeName[] = ["shadcn-theme"];

export type KcEnvName =
    | "SHADCN_THEME_LOGO_URL"
    | "SHADCN_THEME_LOGO_DARK_URL"
    | "SHADCN_THEME_LAYOUT"
    | "SHADCN_THEME_ASIDE_IMAGE_URL"
    | "SHADCN_THEME_CARD_IMAGE_URL"
    | "SHADCN_THEME_SIDE_PANEL_IMAGE_URL"
    | "SHADCN_THEME_SIDE_PANEL_IMAGE_DARK_URL"
    | "SHADCN_THEME_PRESET"
    | "SHADCN_THEME_BASE"
    | "SHADCN_THEME_RADIUS"
    | "SHADCN_THEME_FONT"
    | "SHADCN_THEME_SHOW_PLACEHOLDER"
    | "SHADCN_THEME_SHOW_REALM_NAME"
    | "SHADCN_THEME_SIDE_PANEL_POSITION"
    | "SHADCN_THEME_WELCOME_MESSAGE";

export const kcEnvNames: KcEnvName[] = [
    "SHADCN_THEME_LOGO_URL",
    "SHADCN_THEME_LOGO_DARK_URL",
    "SHADCN_THEME_LAYOUT",
    "SHADCN_THEME_ASIDE_IMAGE_URL",
    "SHADCN_THEME_CARD_IMAGE_URL",
    "SHADCN_THEME_SIDE_PANEL_IMAGE_URL",
    "SHADCN_THEME_SIDE_PANEL_IMAGE_DARK_URL",
    "SHADCN_THEME_PRESET",
    "SHADCN_THEME_BASE",
    "SHADCN_THEME_RADIUS",
    "SHADCN_THEME_FONT",
    "SHADCN_THEME_SHOW_PLACEHOLDER",
    "SHADCN_THEME_SHOW_REALM_NAME",
    "SHADCN_THEME_SIDE_PANEL_POSITION",
    "SHADCN_THEME_WELCOME_MESSAGE",
];

export const kcEnvDefaults: Record<KcEnvName, string> = {
    SHADCN_THEME_LOGO_URL: "",
    SHADCN_THEME_LOGO_DARK_URL: "",
    SHADCN_THEME_LAYOUT: "two-column",
    SHADCN_THEME_ASIDE_IMAGE_URL: "",
    SHADCN_THEME_CARD_IMAGE_URL: "",
    SHADCN_THEME_SIDE_PANEL_IMAGE_URL: "",
    SHADCN_THEME_SIDE_PANEL_IMAGE_DARK_URL: "",
    SHADCN_THEME_PRESET: "neutral",
    SHADCN_THEME_BASE: "neutral",
    SHADCN_THEME_RADIUS: "default",
    SHADCN_THEME_FONT: "geist",
    SHADCN_THEME_SHOW_PLACEHOLDER: "true",
    SHADCN_THEME_SHOW_REALM_NAME: "true",
    SHADCN_THEME_SIDE_PANEL_POSITION: "right",
    SHADCN_THEME_WELCOME_MESSAGE: "",
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext = import("./login/KcContext").KcContext;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login":
                        return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}

// NOTE: This is exported here only because in Webpack environnement it works differently
export const BASE_URL = import.meta.env.BASE_URL;

// NOTE: This is only exported here because you're supposed to import type from different packages
// Depending of if you are using Vite, Webpack, ect...
export type { Meta, StoryObj } from "@storybook/react-vite";
